### ISSUE TITLE
v4 Roadmap

### ISSUE THREAD

**Issue by yannickcr** [yannickcr/eslint-plugin-react#436]
There is a few things that I'd like to changes for a while (default configuration changes, rules renaming/suppression and a few others) and with the upcoming ESLint `v2.0.0` release I think it is the right time to do this.

So here's what I have in mind for now:

* [x] [ESLint 2.0.0 compatibility](http://eslint.org/docs/2.0.0/user-guide/migrating-to-2.0.0)
  * [x] Remove `rulesConfig` and export a shareable config (#192, [documentation](http://eslint.org/docs/2.0.0/user-guide/migrating-to-2.0.0#plugins-no-longer-have-default-configurations))
  * [x] Stop using the `context` deprecated methods and use `sourceCode` ([documentation](http://eslint.org/docs/developer-guide/working-with-rules#the-context-object))
* [x] Definitely remove `jsx-quotes` (PR #433)
* [x] Add static method support to `sort-comp` (#128, PR #429)
* [x] Rename `jsx-sort-prop-types` to `sort-prop-types`
 (#87, PR #431)
* [x] In `display-name`, ~~set the acceptTranspilerName option to true by default~~ invert `acceptTranspilerName` option and rename it `ignoreTranspilerName`.

Do you see anything else that could be good to change/improve?

**Comment by ljharb** [comment]
v2.0.0 is now released - time to get that out ASAP :-D

**Comment by yannickcr** [comment]
It's should be done during this week-end :)

**Comment by yannickcr** [comment]
Just published `4.0.0-rc.0` on npm, you can test it by running:

```bash
$ npm install eslint-plugin-react@next
```

Let me know if you find any issue or if you have suggestions about the new recommended configuration.

**Comment by lukekarrys** [comment]
Thanks @yannickcr. v4 looks pretty good to me.

I did find one bug that I opened here: https://github.com/yannickcr/eslint-plugin-react/issues/443. I think it is due to https://github.com/yannickcr/eslint-plugin-react/commit/b2661aae3146f137032b4a5f8a7aef5e51bc7e67, but I'm not sure how to differentiate stateless component functions from other functions with destructured arguments.

**Comment by yannickcr** [comment]
Thanks @lukekarrys, the issue should be fixed in 6643f8775851d765ce922b09f1826d0053d870a6.

I will publish another RC tomorrow.

**Comment by yannickcr** [comment]
Just published `4.0.0-rc.1` on npm.

**Comment by lukekarrys** [comment]
Thanks @yannickcr. I'm using rc.1 across three different projects now with no issues :smile:

**Comment by Lysholm** [comment]
Thanks @yannickcr! Seconding @lukekarrys sentiment, no problems with rc.1 in my two projects.

**Comment by yannickcr** [comment]
Happy to hear it! In this case, I think I will publish `4.0.0` tomorrow (same as `rc.1` with a [few documentation fixes](https://github.com/yannickcr/eslint-plugin-react/compare/v4.0.0-rc.1...master)).

**Comment by diorahman** [comment]
Nice!

**Comment by yannickcr** [comment]
`4.0.0` is now published
