### ISSUE TITLE
Roadmap v6.0.0

### ISSUE THREAD

**Issue by yannickcr** [yannickcr/eslint-plugin-react#686]
So here's what I have in mind for now:

* [x] Add ESLint as a peerDependency (PR #657)
* [x] Add `all` configuration (#674, PR #683)
* [x] Remove deprecated `jsx-sort-prop-types` rule (#549)
* [x] Remove rules deprecated options (like https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md) (PR #700)
* [x] Rename some JSX-specific rules to include `jsx-` prefix (keep old rules with a warning like `jsx-sort-prop-types`) (#668, PR #689)
* [x] Add `findDOMNode()` warning rule (#678)
* [x] Enable `allow-in-func` mode by default in `no-did-mount-set-state` and `no-did-update-set-state` rules (PR #702)
* [x] Solve `recommended` configuration discussions and update it accordingly (PR #636, #596)
* [x] Support ESLint 3 and new rule format (#661, PR #699)

Do you see anything else that could be good to change/improve?

**Comment by ljharb** [comment]
That seems good to me.

**Comment by ljharb** [comment]
5 down, 4 to go!

**Comment by lencioni** [comment]
On this roadmap, you have

> Enable allow-in-func mode by default in no-did-mount-set-state and no-did-update-set-state rules

I'm not entirely sure what you want done here? Does this amount to removing the option and just having it always be the case, or should this be the case by default and there would be a new option like `disallow-in-func`?

**Comment by yannickcr** [comment]
> should this be the case by default and there would be a new option like `disallow-in-func`

I was more thinking about something like this.

**Comment by ljharb** [comment]
It looks like the last 3 issues all have PRs up - how quickly do you think we could get to a v6?

**Comment by yannickcr** [comment]
@ljharb I hope to publish an RC before friday and the final this week-end if there is no major issue.

**Comment by ljharb** [comment]
@yannickcr there's still one unchecked item on the list - is that punted to v7?

**Comment by petersendidit** [comment]
I just rebased #699 so it should be able to be merged cleanly.

**Comment by yannickcr** [comment]
@ljharb no, still planned for v6 :)

**Comment by ljharb** [comment]
Should this be reopened until that's merged?

**Comment by yannickcr** [comment]
Yep

**Comment by ljharb** [comment]
@yannickcr any more things to add to the above checklist, or are we good for a final release? :-)

**Comment by yannickcr** [comment]
Still a few changes and I think I'll be good to push an RC in the coming hours.

**Comment by yannickcr** [comment]
`v6.0.0-rc.0` is not published on npm.

You can install it with `npm install eslint-plugin-react@next`

**Comment by ljharb** [comment]
I see rc.1 is out. Is there a planned time to release v6?

**Comment by nwhitmont** [comment]
What's the timeline on this?  Appears to be blocking [airbnb eslint config installation](https://www.npmjs.com/package/eslint-config-airbnb) --https://github.com/airbnb/javascript/issues/936

**Comment by yannickcr** [comment]
@ljharb @nwhitmont `v6.0.0` should be released in the coming hours.

**Comment by yannickcr** [comment]
`v6.0.0` is now published on npm

**Comment by lencioni** [comment]
Thanks for all of your hard work on this plugin @yannickcr! This plugin has greatly helped me and my teams over the past couple of years, and I just wanted to make sure you feel appreciated for the effort you put in here. This is such an valuable tool that you've built. 👏  👏  👏 

Thinking ahead to future major version bumps, I'm wondering--is there anything that I (or others who are interested) can do to help make sure that things continue to run smoothly? I don't want you to feel like you are running this thing all by yourself.

**Comment by nwhitmont** [comment]
Thank you @yannickcr !

**Comment by yannickcr** [comment]
Thank you all for your support 😍 , and thanks for your contributions @lencioni 😃 

> Thinking ahead to future major version bumps, I'm wondering--is there anything that I (or others who are interested) can do to help make sure that things continue to run smoothly? I don't want you to feel like you are running this thing all by yourself.

Well, there is more and more open issues and PRs to review/validate and I have some difficulties to keep up with all of this. I added @ljharb as a contributor a few months ago and he made a really great work on issues triage, PRs validation and responding to users questions ❤️ . So I'm now thinking about adding more people as contributors.

Would you be interested to be added as contributor @lencioni?

**Comment by ljharb** [comment]
I'm biased because I work with @lencioni, but I highly endorse his being added!

**Comment by lencioni** [comment]
> Would you be interested to be added as contributor @lencioni?

Sure!

**Comment by yannickcr** [comment]
Done :)
